AWSTemplateFormatVersion: "2010-09-09"
Description: This creates an ASG and a mountable resource
Resources:
    myASG:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties: 
            AvailabilityZones: 
                Fn::GetAZs: !Ref AWS::Region
            AutoScalingGroupName: !Sub asg-${AWS::StackName}
            Cooldown: 5
            LaunchTemplate: 
                LaunchTemplateName:  !Sub lt-${AWS::StackName}
                Version: !GetAtt myLaunchTemplate.LatestVersionNumber
            MaxSize: 2
            MinSize: 1
            DesiredCapacity: 1

    myLaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        Properties: 
            LaunchTemplateData: 
                IamInstanceProfile:
                    Name: ssmRole
                ImageId: ami-0e01ce4ee18447327
                InstanceType: t2.micro
                SecurityGroups: 
                    - mySG
                UserData:
                    Fn::Base64:
                        !Sub |
                            #!/bin/bash
                            instanceId=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document |jq -r .instanceId)
                            instanceRegion=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document |jq -r .region)
            LaunchTemplateName: !Sub lt-${AWS::StackName}

    asgScheduler:
        Type: AWS::AutoScaling::ScheduledAction
        Properties:
            AutoScalingGroupName: 
                Ref: myASG
            MaxSize: 2
            MinSize: 0
            DesiredCapacity: 0
            Recurrence: "0 20-23,0-8 * * *"
    
    lifeCycleHook:
        Type: AWS::AutoScaling::LifecycleHook
        Properties: 
            AutoScalingGroupName: !Ref myASG
            DefaultResult: ABANDON
            HeartbeatTimeout: 30           
            LifecycleTransition: autoscaling:EC2_INSTANCE_LAUNCHING
    
